### PR TITLE
Fix hints not showing up

### PR DESCRIPTION
**Pull request by KoffeinFlummi**
Hints weren't showing up on my system, seems like no one else was having this issue. This fixes it.

### CODE REVIEW

**Comment by jonpas** [comment]
Your system must hate you.

**Comment by KoffeinFlummi** [comment]
Nope, RHS broke it.

**Comment by jonpas** [comment]
How so, does that mean it will brake it for us as well?

**Comment by Pleasure0102** [comment]
I also have no hints with the latest master

**Comment by KoffeinFlummi** [comment]
This is caused by some faulty inheritance in RHS. Load AGM before RHS; that should fix it.

**Comment by jonpas** [comment]
Is that all AGM hints or something specific?

**Pull request closed without merging**
