### PR TITLE
Show friendly sides nametags

### PR DESCRIPTION
**Pull request by BaerMitUmlaut**
See #2020

### CODE REVIEW

**Comment by esteldunedain** [comment]
Thanks, perfect!

I don't like how we use `playerSide` there, but that's independent of your change. I assume you tested this, right?

**Comment by BaerMitUmlaut** [comment]
Yes. Standard value of getFriend seems to be 1 or -1 and if you friendly fire too much and your side only constists of you it instantly goes to -1.
I'm not sure when a different value gets applied, if your side consists of more units then the getFriend value stays at 1.

**Comment by esteldunedain** [comment]
True. Thanks for the contrib!

**Comment by esteldunedain** [comment]
Hey, wait a sec. You have to change the exact same thing on line:

https://github.com/KoffeinFlummi/AGM/pull/2031/files#diff-12bd30917ec23106faea4164d491f4e1L39

If not this only works for cursor mode. Could you do it?

**Comment by esteldunedain** [comment]
nvm

**Comment by BaerMitUmlaut** [comment]
My bad, overlooked that one.

**Comment by esteldunedain** [comment]
No problem

**Pull request merged**
