### PR TITLE
Fixed buggy arm in lowered run

### PR DESCRIPTION
**Pull request by evromalarkey**
When you're running with the lowered weapon and you press C (combat pace), there was buggy arm. I've changed the anim, so it looks better.

### CODE REVIEW

**Comment by commy2** [comment]
WIP tag is just a reminder for me.

**Comment by commy2** [comment]
This basically nukes the tactical walk. Not sure if I want this.

**Comment by commy2** [comment]
Please test if it still looks funky with https://github.com/KoffeinFlummi/AGM/issues/2095

**Comment by evromalarkey** [comment]
why not include the alternative animation I've added? In my opinion, with the current animation players are running like retards with the lowered stance.. the new one is more natural

**Comment by commy2** [comment]
>This basically nukes the tactical walk. Not sure if I want this.

**Pull request closed without merging**
