### PR TITLE
Fixed Medical Module typo and made descriptions consistent

### PR DESCRIPTION
**Pull request by jonpas**
The inconsistency bothered me, can revert if you liked it the old way more.

### CODE REVIEW

**Comment by licht-im-Norden87** [comment]
As far as i know nouns are not capitals

**Comment by jonpas** [comment]
True, but it emphasizes the items that can or can't be used.

**Comment by commy2** [comment]
Isn't the item called Epipen though? Epinephrines sounds like you arrange individual molecules, lol.

**Comment by jonpas** [comment]
On another thought, Epinephrine should be singular anyways, I'll fix that.

**Comment by Cuel** [comment]
http://upload.wikimedia.org/wikipedia/commons/6/60/Epipen.jpg

It is called EpiPen

seems to be a registered trademark tho.

**Comment by jonpas** [comment]
Yeah, it's a trademarked nickname as I see it, but it's Epinephrine nevertheless.

**Comment by jonpas** [comment]
On a new fork branch in #1953

**Pull request closed without merging**
